services:
  postgres:
    container_name: genie_pg_sql
    image: postgres
    environment:
        POSTGRES_USER: ujjwal
        POSTGRES_PASSWORD: ujjwal
        POSTGRES_DB: genie_project
        PGDATA: /data/postgres
        TZ: UTC
    volumes:
          - postgres:/data/postgres
    ports:
          - 5433:5432
    networks:
          - genieService-network
    restart: unless-stopped

  pgadmin:
        container_name: genie_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            TZ: UTC

        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - 5051:80
        networks:
            - genieService-network
        restart: unless-stopped

networks:
  genieService-network:
    driver: bridge


volumes:
    postgres:
    pgadmin: