spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/genie_project
    username: ujjwal
    password: ujjwal
    driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
        ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: genieBackend


server:
  port: 8098

application:
  config:
    GEMINI_API_KEY: AIzaSyD7coKlIb1Wey8P2rHVHYoaiHB4stzCbZE
    GOOGLE_CSE_API_KEY: AIzaSyCQsL9ABcDKGe-eLtkPkKfYbzI08KZ3Dvo
    GOOGLE_CSE_CX: a2ca579b02db84b73

debug: true
