spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/genie_project
    username: ujjwal
    password: ujjwal
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: genieBackend



server:
  port: 8098

application:
  config:
    GEMINI_API_KEY: AIzaSyD7coKlIb1Wey8P2rHVHYoaiHB4stzCbZE
debug: true
